#!/bin/bash
#Assignment 2
#Author: Emily VanDerveer
#This script sends a customized mail message to user listed 
#on the command line if they are logged in.
#
#usage: mailFun username
#
#

function mailMessage () {
	echo "Hello $recipiant, 
	******This email is automatically generated by $USER *******
	My instructor requires that I send this message as part of an 
	assignment for class 92.312. The current date 
	and time is $NOW. 
	Have a nice day.
	$fullName" | mailx -s "automatic email" $var
	echo message sent to $var
}

if [ -z "$1" ]
	then
	echo "Error. No username was indicated." 1>&2
	exit 1;
	fi

fullName=$(cat /etc/passwd | grep "$USER": | cut -d: -f5 | tr -d [=,=]);	#Cuts the Full Name from field 5 
																			#of the passwd file for the user

for var in $@
	do
		recipiant=$(cat /etc/passwd | grep "$var": | cut -d: -f5 | tr -d [=,=]);	#Cuts recipiants Full name from field 5
		cat /etc/passwd | grep -q -o -w "$var"			#searches passwd for exact word match of $var
		if [ $? -eq 0 ]
		then
			users | grep -o -q -w "$var"
			if [ $? -eq 0 ]
			then
				NOW=$(date +"%m-%d-%Y %r")
				mailMessage
			else
				echo "$var not logged in"
			fi
		else
			echo "$var does not exist" 
			
		fi
	done
